### ISSUE TITLE
logic behind persistence and can it apply to vm370 under hercules under docker as well

### ISSUE THREAD

**Issue by kwccoin** [joergschultzelutter/tk5-hercules#1]
Under you are more onto mvs (and has used yours for quite a while in old times).  But given this command and not familar with docker, is this about directing docker to treat certain files as real (external) files and even directories (as it seems even dasd is covered) here.  And if so, is the VM sixpack also can be covered and VSE 5 pack?

Just curious as I were told to handle the persistance issue via image level (so not to go to older image but use the latest or commit each time and use it as the starting point).

Apology for asking.

**Comment by joergschultzelutter** [comment]
No need for apologies - and thank you for your inquiry. 

The Docker script in question is literally a clone of the existing tk4 script which -in addition- was also ported to Alpine Linux for more efficient memory usage. I am not a Docker expert either :-) 

The first part of the script creates the initial image, pulls the tk5 files from [here](https://www.prince-webdesign.nl/tk5) and moves them to their correct location(s). The second part then exposes several directories from the Docker container (see https://github.com/skunklabz/tk4-hercules?tab=readme-ov-file#persistence) to the user in case persistence is required.

If you point me to the VM sixpack / VSE 5 pack files, I'll have a look and see if these files can get incorporated as well. Note that the materials listed as "optional" (see [here](https://www.prince-webdesign.nl/tk5) at the bottom of the page) are also not incorporated as they require one initial installation run from within the Hercules emulator.

**Comment by joergschultzelutter** [comment]
Closing this issue for now as there was no update; please feel free to open another ticket in case there are still questions left.
