### ISSUE TITLE
Broken member of the MVS Source

### ISSUE THREAD

**Issue by SE20225** [joergschultzelutter/tk5-hercules#2]
I have had much use of the Source volumes from the TK4-system.  But when looking at member IECIOSCN in SYM102.F19 on SRC000, it is very obvious that it is not complete. The last statement happens to be a TITLE.
If I remember correctly, the souce files may have been moved to a single volume in TK5, but is there any change made? 
Somebody has a copy downloaded and can easily check? 

andersedlund@telia.com

**Comment by joergschultzelutter** [comment]
I'm afraid that I cannot help here - the author of the zip package which is digested by the docker file would probably need to fix things inside of that zip file.

Contact details: [https://www.prince-webdesign.nl/index.php/contact](https://www.prince-webdesign.nl/index.php/contact)
This is the web site for the package which gets digested by the Docker file: [https://www.prince-webdesign.nl/tk5](https://www.prince-webdesign.nl/tk5)
